# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Committed < Formula
  desc "WYSIWYG Git commit editor that helps improve the quality of your commits by showing you the layout in the same format as git log"
  homepage "https://github.com/mikelorant/committed"
  version "0.6.2"
  license "MIT"

  depends_on "git"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mikelorant/committed/releases/download/v0.6.2/committed_0.6.2_darwin_arm64.tar.gz"
      sha256 "0bf68ef1043c2f36975e8b4531854d5e0de716c40d7a19aa60edc759e52f41d3"

      def install
        bin.install "committed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikelorant/committed/releases/download/v0.6.2/committed_0.6.2_darwin_amd64.tar.gz"
      sha256 "d7a979dafa9346fae34c5bc7a65a0f2e332eaf2d79658c90af7ab366781bb3fb"

      def install
        bin.install "committed"
      end
    end
  end

  test do
    system "#{bin}/committed --help"
  end
end
