# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Committed < Formula
  desc "WYSIWYG Git commit editor that helps improve the quality of your commits by showing you the layout in the same format as git log"
  homepage "https://github.com/mikelorant/committed"
  version "0.10.0"
  license "MIT"

  depends_on "git"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mikelorant/committed/releases/download/v0.10.0/committed_0.10.0_darwin_arm64.tar.gz"
      sha256 "0e763a809f8c8be70ce86d3964de3161c198a8448eb2a1d9ebecf8139154ec8f"

      def install
        bin.install "committed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikelorant/committed/releases/download/v0.10.0/committed_0.10.0_darwin_amd64.tar.gz"
      sha256 "32c968f15c190aafe76bec3fd556c735aad47bf9c063921f39fe7ebfb0d2bf50"

      def install
        bin.install "committed"
      end
    end
  end

  test do
    system "#{bin}/committed --help"
  end
end
